apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-ams-paygops
  name: ph-ee-connector-ams-paygops
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
    - name: http
      port: 82
      protocol: TCP
      targetPort: 8080
  selector:
    app: ph-ee-connector-ams-paygops
  sessionAffinity: None
  type: ClusterIP