{{- if .Values.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-connector-bulk-closedloop
  labels:
    app: ph-ee-connector-bulk-closedloop
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-bulk-closedloop
  template:
    metadata:
      labels:
        app: ph-ee-connector-bulk-closedloop
      annotations:
{{- if .Values.deployment.annotations }}
{{ toYaml .Values.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-connector-bulk-closedloop
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "{{ .Values.limits.memory }}"
              cpu: "{{ .Values.limits.cpu }}"
            requests:
              memory: "{{ .Values.requests.memory }}"
              cpu: "{{ .Values.requests.cpu }}"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.global.SPRING_PROFILES_ACTIVE }}"
            - name: "CAMEL_DISABLE-SSL"
              value: "{{ .Values.camel_disable_ssl }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "{{ .Release.Name }}-zeebe-gateway:26500"
            - name: "TENANTS"
              value: "{{ .Values.tenants }}"
            - name: "APPLICATION_BUCKET-NAME"
              value: "{{ .Values.application.bucket_name }}"
            - name: "OPERATIONS-APP_CONTACTPOINT"
              value: "{{ .Values.operations_app.contactpoint }}"
            - name: "OPERATIONS-APP_ENDPOINTS_BATCH-SUMMARY"
              value: "{{ .Values.operations_app.endpoints.batch-summary }}"
            - name: "OPERATIONS-APP_ENDPOINTS_BATCH-DETAIL"
              value: "{{ .Values.operations_app.endpoints.batch-detail }}"
            - name: "MOCK-PAYMENT-SCHEMA_CONTACTPOINT"
              value: "{{ .Values.mock-payment-schema.contactpoint }}"
            - name: "MOCK-PAYMENT-SCHEMA_ENDPOINTS_BATCH-SUMMARY"
              value: "{{ .Values.mock-payment-schema.endpoints.batch-summary }}"
            - name: "MOCK-PAYMENT-SCHEMA_ENDPOINTS_BATCH-DETAIL"
              value: "{{ .Values.mock-payment-schema.endpoints.batch-detail }}"
            - name: "BULK-PROCESSOR_CONTACTPOINT"
              value: "{{ .Values.bulk-processor.contactpoint }}"
            - name: "BULK-PROCESSOR_ENDPOINTS_BATCH-TRANSACTION"
              value: "{{ .Values.bulk-processor.endpoints.batch-transaction }}"
            - name: "CONFIG_COMPLETION-THRESHOLD-CHECK_COMPLETION-THRESHOLD"
              value: "{{ .Values.config.completion_threshold_check.completion-threshold }}"
            - name: "CONFIG_COMPLETION-THRESHOLD-CHECK_MAX-RETRY-COUNT"
              value: "{{ .Values.config.completion_threshold_check.max-retry-count }}"
            - name: "CONFIG_COMPLETION-THRESHOLD-CHECK_WAIT-TIMER"
              value: "{{ .Values.config.completion_threshold_check.wait-timer }}"
            - name: "TENANT"
              value: "{{ .Values.global.tenant }}"
            - name: "CLOUD_AWS_REGION_STATIC"
              value: "{{ .Values.aws.region }}"
            - name: "AWS_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: "bulk-processor-secret"
                  key: "aws-access-key"
            - name: "AWS_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: "bulk-processor-secret"
                  key: "aws-secret-key"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
{{- end }}