{{- if .Values.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-connector-ams-mifos
  labels:
    app: ph-ee-connector-ams-mifos
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-ams-mifos
  template:
    metadata:
      labels:
        app: ph-ee-connector-ams-mifos
      annotations:
        {{- if .Values.deployment.annotations }}
        {{ toYaml .Values.deployment.annotations | indent 8 }}
        {{- end }}
    spec:
      affinity: 
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      nodeSelector: 
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      tolerations: 
        {{- toYaml ( .Values.tolerations | default .Values.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      serviceAccountName: ph-ee-connector-ams-mifos
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      # --- BEGIN Init Container ---
      initContainers:
        - name: wait-for-gateway
          image: busybox:1.28 # Or another image with nslookup and nc
          command: ['sh', '-c', 'until nslookup phee-zeebe-gateway && nc -z phee-zeebe-gateway 26500; do echo "Waiting for phee-zeebe-gateway (port 26500)..."; sleep 2; done; echo "Gateway is up!"']
      # --- END Init Container ---
      containers:
        - name: ph-ee-connector-ams-mifos
          image: "{{ .Values.image }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          {{- if .Values.resources }}
          {{- include "common.resourceTemplate" . | nindent 8 }}
          {{- end }}
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.SPRING_PROFILES_ACTIVE }}"
            - name: "ams_local_enabled"
              value: "{{ .Values.ams_local_enabled }}"
            - name: "ams_local_interop_host"
              value: "{{ .Values.ams_local_interop_host }}"
            - name: "ams_local_customer_host"
              value: "{{ .Values.ams_local_customer_host }}"
            - name: "ams_local_account_host"
              value: "{{ .Values.ams_local_account_host }}"
            - name: "ams_local_auth_host"
              value: "{{ .Values.ams_local_auth_host }}"
            - name: "ams_local_loan_host"
              value: "{{ .Values.ams_local_loan_host }}"
            - name: "DFSPIDS"
              value: "{{ .Values.global.DFSPIDS }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "{{ .Release.Name }}-zeebe-gateway:26500"
            - name: "ZEEBE_CLIENT_MAX-EXECUTION-THREADS"
              value: "{{ .Values.global.max_execution_threads }}"
            - name: "ZEEBE_CLIENT_POLL-INTERVAL"
              value: "{{ .Values.global.poll_interval }}"
            {{- if .Values.extraEnvs | default .Values.deployment.extraEnvs }}
            {{ toYaml ( .Values.extraEnvs | default .Values.deployment.extraEnvs ) | indent 12 }}
            {{- end }}
          {{- if .Values.envFrom | default .Values.deployment.envFrom }}
          envFrom:
            {{ toYaml ( .Values.envFrom | default .Values.deployment.envFrom ) | nindent 12 }}
          {{- end }}
          securityContext: 
            {{ toYaml ( .Values.podSecurityContext | default .Values.deployment.securityContext ) | nindent 12 }}
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
          # {{- if .Values.deployment.config }}
          # {{ toYaml .Values.deployment.config | indent 12 }}
          # {{- end }}
      initContainers:
        - name: wait-db
          image: busybox:1.35
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for database connection..."
              until nc -z {{ .Values.operations_app.datasource.host }} 3306; do
                echo "Database not ready, waiting..."
                sleep 2
              done
              echo "Database is ready!"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
      {{- if .Values.extraContainers }}
      {{ tpl .Values.extraContainers . | indent 6 }}
      {{- end }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
