# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.ph_ee_connector_mojaloop.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ph-ee-connector-mojaloop-java.fullname" . }}
  labels:
    app: "{{ template "ph-ee-connector-mojaloop-java.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: '{{ .Release.Service }}'

  {{- if .Values.ph_ee_connector_mojaloop.deployment.annotations }}
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.ph_ee_connector_mojaloop.replicas }}
  selector:
    matchLabels:
      app: "{{ template "ph-ee-connector-mojaloop-java.fullname" . }}"
  template:
    metadata:
      annotations:
{{- if .Values.ph_ee_connector_mojaloop.deployment.annotations }}
{{ toYaml .Values.ph_ee_connector_mojaloop.deployment.annotations | indent 8 }}
{{- end }}
        configChecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
      labels:
        app: '{{ template "ph-ee-connector-mojaloop-java.fullname" . }}'
        chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    spec:
      affinity: {{ toYaml .Values.ph_ee_connector_mojaloop.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.ph_ee_connector_mojaloop.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.ph_ee_connector_mojaloop.tolerations | default .Values.ph_ee_connector_mojaloop.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.ph_ee_connector_mojaloop.priorityClassName }}
      priorityClassName: {{ .Values.ph_ee_connector_mojaloop.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template "ph-ee-connector-mojaloop-java.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.ph_ee_connector_mojaloop.terminationGracePeriod }}
      {{- if .Values.ph_ee_connector_mojaloop.deployment.hostAliases }}
      hostAliases: {{ toYaml .Values.ph_ee_connector_mojaloop.deployment.hostAliases | nindent 8 }}
      {{- end }}
      volumes:
      {{- range .Values.ph_ee_connector_mojaloop.secretMounts | default .Values.ph_ee_connector_mojaloop.deployment.secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      {{- if .Values.ph-ee-connector-mojaloop-javaConfig }}
      - name: ph-ee-connector-mojaloop-java-config
        configMap:
          defaultMode: 0600
          name: {{ template "ph-ee-connector-mojaloop-java.fullname" . }}-config
      {{- if .Values.ph_ee_connector_mojaloop.extraVolumes | default .Values.ph_ee_connector_mojaloop.deployment.extraVolumes }}
{{ toYaml ( .Values.ph_ee_connector_mojaloop.extraVolumes | default .Values.ph_ee_connector_mojaloop.deployment.extraVolumes ) | indent 6 }}
      {{- end }}

      {{- if .Values.ph_ee_connector_mojaloop.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.ph_ee_connector_mojaloop.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.ph_ee_connector_mojaloop.extraInitContainers }}
      initContainers:
      # All the other beats accept a string here while
      # ph-ee-connector-mojaloop-java accepts a valid yaml array. We're keeping
      # this as a backwards compatible change, while adding
      # also a way to pass a string as other templates to
      # make these implementations consistent.
      # https://github.com/elastic/helm-charts/issues/490
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
      {{- end }}
      {{- end }}
      containers:
      - name: "ph-ee-connector-mojaloop-java"
        image: "{{ .Values.ph_ee_connector_mojaloop.image }}:{{ .Values.ph_ee_connector_mojaloop.imageTag }}"
        imagePullPolicy: "{{ .Values.ph_ee_connector_mojaloop.imagePullPolicy }}"
        ports:
          - containerPort: 5000        
        resources:
            limits:
              memory: "{{ .Values.ph_ee_connector_mojaloop.limits.memory }}"
              cpu: "{{ .Values.ph_ee_connector_mojaloop.limits.cpu }}"
            requests:
              memory: "{{ .Values.ph_ee_connector_mojaloop.requests.memory }}"
              cpu: "{{ .Values.ph_ee_connector_mojaloop.requests.cpu }}"
        args:
          - "-e"
          - "-E"
          - "http.enabled=true"
        livenessProbe:
{{ toYaml .Values.ph_ee_connector_mojaloop.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.ph_ee_connector_mojaloop.readinessProbe | indent 10 }}        
        env:
          - name: "SPRING_PROFILES_ACTIVE"
            value: "{{ .Values.ph_ee_connector_mojaloop.SPRING_PROFILES_ACTIVE }}"

          - name: "DFSPIDS"
            value: "{{ .Values.ph_ee_connector_mojaloop.DFSPIDS }}"

          - name: "SWITCH_quotes-host"
            value: "{{ .Values.ph_ee_connector_mojaloop.switch.quotes.host }}"
 
          - name: "SWITCH_quote-service"
            value: "{{ .Values.ph_ee_connector_mojaloop.switch.quotes.service }}"

          - name: "SWITCH_als-host"
            value: "{{ .Values.ph_ee_connector_mojaloop.switch.als.host }}"

          - name: "SWITCH_account-lookup-service"
            value: "{{ .Values.ph_ee_connector_mojaloop.switch.als.service }}"

          - name: "SWITCH_transfers-host"
            value: "{{ .Values.ph_ee_connector_mojaloop.switch.transfers.host }}"

          - name: "SWITCH_transfers-service"
            value: "{{ .Values.ph_ee_connector_mojaloop.switch.transfers.service }}"

          - name: "SWITCH_transactions-host"
            value: "{{ .Values.ph_ee_connector_mojaloop.switch.transactions.host }}"

          - name: "SWITCH_transaction-request-service"
            value: "{{ .Values.ph_ee_connector_mojaloop.switch.transactions.service }}"

          - name: "SWITCH_oracle-host"
            value: "{{ .Values.ph_ee_connector_mojaloop.switch.oracle.host }}"
{{- if .Values.ph_ee_connector_mojaloop.extraEnvs | default .Values.ph_ee_connector_mojaloop.deployment.extraEnvs }}
{{ toYaml ( .Values.ph_ee_connector_mojaloop.extraEnvs | default .Values.ph_ee_connector_mojaloop.deployment.extraEnvs ) | indent 8 }}
{{- end }}
        envFrom: {{ toYaml ( .Values.ph_ee_connector_mojaloop.envFrom | default .Values.ph_ee_connector_mojaloop.deployment.envFrom ) | nindent 10 }}
        securityContext: {{ toYaml ( .Values.ph_ee_connector_mojaloop.podSecurityContext | default .Values.ph_ee_connector_mojaloop.deployment.securityContext ) | nindent 10 }}
        volumeMounts:
        {{- range .Values.secretMounts | default .Values.ph_ee_connector_mojaloop.deployment.secretMounts }}
        - name: {{ .name }}
          mountPath: {{ .path }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- range $path, $config := .Values.ph-ee-connector-mojaloop-javaConfig }}
        - name: ph-ee-connector-mojaloop-java-config
          mountPath: /usr/share/ph-ee-connector-mojaloop-java/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{ else }}
        {{- range $path, $config := .Values.ph_ee_connector_mojaloop.deployment.ph-ee-connector-mojaloop-javaConfig }}
        - name: ph-ee-connector-mojaloop-java-config
          mountPath: /usr/share/ph-ee-connector-mojaloop-java/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{- end }}
        {{- end }}
        {{- if .Values.ph_ee_connector_mojaloop.extraVolumeMounts | default .Values.ph_ee_connector_mojaloop.deployment.extraVolumeMounts }}
{{ toYaml ( .Values.ph_ee_connector_mojaloop.extraVolumeMounts | default .Values.ph_ee_connector_mojaloop.deployment.extraVolumeMounts ) | indent 8 }}
        {{- end }}
      {{- if .Values.ph_ee_connector_mojaloop.extraContainers }}
{{ tpl .Values.ph_ee_connector_mojaloop.extraContainers . | indent 6 }}
      {{- end }}
{{- end }}