{{- if .Values.enabled -}}
apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: roster-secret
type: Opaque
data:
  auth-token: {{ .Values.pesacore.auth_header | b64enc }}
{{- end }}
