{{- if .Values.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-zeebe-ops
  labels:
    app: ph-ee-zeebe-ops
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ph-ee-zeebe-ops
  template:
    metadata:
      labels:
        app: ph-ee-zeebe-ops
      annotations:
{{- if .Values.deployment.annotations }}
{{ toYaml .Values.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      initContainers:
      {{- with .Values.extraInitContainers }}
      {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: ph-ee-zeebe-ops
          image: "{{ .Values.image }}"
          imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.limits.memory }}"
              cpu: "{{ .Values.limits.cpu }}"
            requests:
              memory: "{{ .Values.requests.memory }}"
              cpu: "{{ .Values.requests.cpu }}"
          ports:
            - containerPort: 5000
          env:
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "{{ .Release.Name }}-zeebe-gateway:26500"
            - name: "TENANTS"
              value: "{{ .Values.global.tenants }}"
            - name: "DFSPIDS"
              value: "{{ .Values.global.DFSPIDS }}"           
            - name: "elasticsearch_url"
              value: "{{ .Values.elasticsearch_url }}"
            - name: "LOGGING_LEVEL_ROOT"
              value:  "{{ .Values.global.LOGGING_LEVEL_ROOT }}"
            - name: "SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS"
              value: "{{ .Values.elasticsearch_contactpoint }}"
            - name: "ELASTICSEARCH_SECURITY_ENABLED"
              value: "{{ .Values.elasticsearch_security_enabled }}"
            - name: "ELASTICSEARCH_SSLVERIFICATION"
              value: "{{ .Values.elasticsearch_sslverification }}"
            - name: "ELASTICSEARCH_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: username
            - name: "ELASTICSEARCH_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: password
{{- if .Values.extraEnvs | default .Values.deployment.extraEnvs }}
{{ toYaml ( .Values.extraEnvs | default .Values.deployment.extraEnvs ) | indent 10 }}
{{- end }}        
          envFrom: {{ toYaml ( .Values.envFrom | default .Values.deployment.envFrom ) | nindent 12 }}
          securityContext: {{ toYaml ( .Values.podSecurityContext | default .Values.deployment.securityContext ) | nindent 12 }}              


{{- end }}
