{{- if .Values.zeebe_ops.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-zeebe-ops"
  labels:
    app: ph-ee-zeebe-ops
spec:
  replicas: {{ .Values.zeebe_ops.replicas }}
  selector:
    matchLabels:
      app: ph-ee-zeebe-ops
  template:
    metadata:
      labels:
        app: ph-ee-zeebe-ops
      annotations:
{{- if .Values.zeebe_ops.deployment.annotations }}
{{ toYaml .Values.zeebe_ops.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-zeebe-ops
          image: "{{ .Values.zeebe_ops.image }}:{{ .Values.zeebe_ops.imageTag }}"
          imagePullPolicy: "{{ .Values.zeebe_ops.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.zeebe_ops.limits.memory }}"
              cpu: "{{ .Values.zeebe_ops.limits.cpu }}"
            requests:
              memory: "{{ .Values.zeebe_ops.requests.memory }}"
              cpu: "{{ .Values.zeebe_ops.requests.cpu }}"
          ports:
            - containerPort: 5000
          env:
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "{{ .Values.zeebe_ops.zeebe_broker_contactpoint }}"
            - name: "TENANTS"
              value: "{{ .Values.zeebe_ops.tenants }}"
            - name: "elasticsearch_url"
              value: "{{ .Values.zeebe_ops.elasticsearch_url }}"
            - name: "LOGGING_LEVEL_ROOT"
              value:  "{{ .Values.zeebe_ops.LOGGING_LEVEL_ROOT }}"
            - name: "SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS"
              value: "{{ .Values.zeebe_ops.elasticsearch_contactpoint }}"
            - name: "ELASTICSEARCH_SECURITY_ENABLED"
              value: "{{ .Values.zeebe_ops.elasticsearch_security_enabled }}"
            - name: "ELASTICSEARCH_SSLVERIFICATION"
              value: "{{ .Values.zeebe_ops.elasticsearch_sslverification }}"
            - name: "ELASTICSEARCH_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: username
            - name: "ELASTICSEARCH_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: password
{{- end }}                  