service:
  apiVersion: "v1"

secret:
  apiVersion: "v1"

configmap:
  apiVersion: "v1"

enabled: true
image: docker.io/openmf/ph-ee-identity-account-mapper:latest
imagePullPolicy: "Always"
hostname: "identity-mapper.sandbox.mifos.io"
limits:
  cpu: "500m"
  memory: "512M"
requests:
  cpu: "100m"
  memory: "256M"
LOGGING_LEVEL_ROOT: INFO

async:
  core_pool_size: 10
  max_pool_size: 10
  queue_capacity: 100
account_validation_enabled: "false"
account_validator_connector: "gsma"

spring:
  cache:
    time_to_live: 30
    time_to_idle: 30
    max_entries_heap: 1000
    max_byte_off_heap: 10
    max_byte_disk: 10
  datasource:
    url: jdbc:mysql:thin://operationsmysql:3306/identity_account_mapper
    username: mifos
    password: password




ingress:
  enabled: true
  annotations: {}
  # kubernetes.io/ingress.class: "nginx"
  pathtype: Prefix
  hosts:
    - host: ""
      paths:
        - path: /
  tls: []
  #  - secretName: sandbox-secret
  #    hosts:
  #      - chart-example.local

deployment:
  apiVersion: "apps/v1"
  annotations:
    deployTime: "{{ .Values.deployTime }}"