service:
  apiVersion: "v1"

secret:
  apiVersion: "v1"

configmap:
  apiVersion: "v1"

enabled: true
replicas: 1
image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-identity-account-mapper"
imagetag: latest
SPRING_PROFILES_ACTIVE: "bb"
limits:
  cpu: "500m"
  memory: "512M"
requests:
  cpu: "100m"
  memory: "256M"
deployment:
  apiVersion: "apps/v1"
  annotations:
    deployTime: "{{ .Values.deployTime }}"

LOGGING_LEVEL_ROOT : ""
async:
  core_pool_size: "10"
  max_pool_size: "10"
  queue_capacity: "100"
account_validation_enabled: "false"
account_validator_connector: "gsma"
gsma_connector:
  contactpoint: ""
mojaloop_connector:
  contactpoint: ""
hostname: "identity-accouunt.fynarfin.sandbox.io"

datasource:
  url: jdbc:mysql:thin://operationsmysql:3306/IdentityAccountMapper
  username: mifos
  password: password




ingress:
  enabled: true
  hostname: "identity.sandbox.fynarfin.io"
  path: "/"
  wildcardhostname: "*.sandbox.fynarfin.io"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "200m"
    memory: "0.5Gi"