{{- if .Values.enabled -}}
apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: paygops-secret
type: Opaque
data:
  auth-token: {{ .Values.paygops.authheader | b64enc }}
{{- end }}
