{{- if .Values.enabled -}}
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph_ee_identity_account_mapper
  name: ph_ee_identity_account_mapper
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph_ee_identity_account_mapper
  sessionAffinity: None
  type: ClusterIP
  {{- end }}