dependencies:
- name: ph-ee-engine
  repository: https://fynarfin.io/images/ph-ee-engine
  version: 1.8.1-SNAPSHOT

- name: ph_ee_identity_account_mapper
  version: 1.0.0
  repository: "file://../identity-account-mapper/account-mapper"