{{- if .Values.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-connector-slcb
  labels:
    app: ph-ee-connector-slcb
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-slcb
  template:
    metadata:
      labels:
        app: ph-ee-connector-slcb
      annotations:
{{- if .Values.deployment.annotations }}
{{ toYaml .Values.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      initContainers:
      {{- with .Values.extraInitContainers }}
      {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: ph-ee-connector-slcb-mm
          image: "{{ .Values.image }}"
          imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "{{ .Values.limits.memory }}"
              cpu: "{{ .Values.limits.cpu }}"
            requests:
              memory: "{{ .Values.requests.memory }}"
              cpu: "{{ .Values.requests.cpu }}"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.global.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "{{ .Release.Name }}-zeebe-gateway:26500" 
            - name: "SLCB_AUTH_HOST"
              value: "{{ .Values.auth_host }}"
            - name: "SLCB_AUTH_AUTH-ENDPOINT"
              value: "{{ .Values.endpoint.auth }}"
            - name: "SLCB_API_HOST"
              value: "{{ .Values.api_host }}"
            - name: "SLCB_API_TRANSACTION-REQUEST-ENDPOINT"
              value: "{{ .Values.endpoint.transaction_request }}"
            - name: "SLCB_API_RECONCILIATION-ENDPOINT"
              value: "{{ .Values.endpoint.reconciliation }}"
            - name: "SLCB_API_ACCOUNT-BALANCE-ENDPOINT"
              value: "{{ .Values.endpoint.account_balance }}"
            - name: "SLCB_CONFIG_DATE-FROMAT"
              value: "{{ .Values.config.date_format }}"
            - name: "SLCB_CONFIG_RECONCILIATION_ENABLE"
              value: "{{ .Values.config.reconciliation.enable }}"
            - name: "SLCB_ACCOUNT_NUMBER"
              value: "{{ .Values.account_number }}"
            - name: "SLCB_ACCOUNT_TYPE"
              value: "{{ .Values.account_type }}"
            - name: "SLCB_INSTITUTIONCODE"
              value: "{{ .Values.institutioncode }}"
            - name: "AWS_BUCKET_NAME"
              value: "{{ .Values.aws.bucket_name }}"
            - name: "CLOUD_AWS_REGION_STATIC"
              value: "{{ .Values.aws.region }}"
            - name: "AWS_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "aws-access-key"
            - name: "AWS_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "aws-secret-key"
            - name: "SLCB_AUTH_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "slcb-username"  
            - name: "SLCB_AUTH_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "slcb-password"
            - name: "SLCB_SIGNATURE_KEY"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "slcb-signature-key"
{{- if .Values.extraEnvs | default .Values.deployment.extraEnvs }}
{{ toYaml ( .Values.extraEnvs | default .Values.deployment.extraEnvs ) | indent 10 }}
{{- end }}        
          envFrom: {{ toYaml ( .Values.envFrom | default .Values.deployment.envFrom ) | nindent 12 }}
          securityContext: {{ toYaml ( .Values.podSecurityContext | default .Values.deployment.securityContext ) | nindent 12 }}              

          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
{{- end }}
