{{- if .Values.enabled -}}
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-slcb
  name: ph-ee-connector-slcb
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-slcb
  sessionAffinity: None
  type: ClusterIP
{{- end }}  