# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.operations.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ph-ee-importer-rdbms.fullname" . }}
  labels:
    app: "{{ template "ph-ee-importer-rdbms.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: '{{ .Release.Service }}'

  {{- if .Values.importer_rdbms.deployment.annotations }}
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.importer_rdbms.replicas }}
  selector:
    matchLabels:
      app: "{{ template "ph-ee-importer-rdbms.fullname" . }}"
  template:
    metadata:
      annotations:
{{- if .Values.importer_rdbms.deployment.annotations }}
{{ toYaml .Values.importer_rdbms.deployment.annotations | indent 8 }}
{{- end }}
        configChecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
      labels:
        app: '{{ template "ph-ee-importer-rdbms.fullname" . }}'
        chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    spec:
      affinity: {{ toYaml .Values.importer_rdbms.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.importer_rdbms.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.importer_rdbms.tolerations | default .Values.importer_rdbms.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.importer_rdbms.priorityClassName }}
      priorityClassName: {{ .Values.importer_rdbms.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template "ph-ee-importer-rdbms.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.importer_rdbms.terminationGracePeriod }}
      {{- if .Values.importer_rdbms.deployment.hostAliases }}
      hostAliases: {{ toYaml .Values.importer_rdbms.deployment.hostAliases | nindent 8 }}
      {{- end }}
      volumes:
      {{- range .Values.importer_rdbms.secretMounts | default .Values.importer_rdbms.deployment.secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      {{- if .Values.ph-ee-importer-rdbmsConfig }}
      - name: ph-ee-importer-rdbms-config
        configMap:
          defaultMode: 0600
          name: {{ template "ph-ee-importer-rdbms.fullname" . }}-config
      {{- if .Values.importer_rdbms.extraVolumes | default .Values.importer_rdbms.deployment.extraVolumes }}
{{ toYaml ( .Values.importer_rdbms.extraVolumes | default .Values.importer_rdbms.deployment.extraVolumes ) | indent 6 }}
      {{- end }}

      {{- if .Values.importer_rdbms.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.importer_rdbms.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.importer_rdbms.extraInitContainers }}
      initContainers:
      # All the other beats accept a string here while
      # ph-ee-importer-rdbms accepts a valid yaml array. We're keeping
      # this as a backwards compatible change, while adding
      # also a way to pass a string as other templates to
      # make these implementations consistent.
      # https://github.com/elastic/helm-charts/issues/490
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
      {{- end }}
      {{- end }}
      containers:
      - name: "ph-ee-importer-rdbms"
        image: "{{ .Values.importer_rdbms.image }}:{{ .Values.importer_rdbms.imageTag }}"
        imagePullPolicy: "{{ .Values.importer_rdbms.imagePullPolicy }}"
        ports:
          - containerPort: 5000        
        resources:
            limits:
              memory: "{{ .Values.importer_rdbms.limits.memory }}"
              cpu: "{{ .Values.importer_rdbms.limits.cpu }}"
            requests:
              memory: "{{ .Values.importer_rdbms.requests.memory }}"
              cpu: "{{ .Values.importer_rdbms.requests.cpu }}"
        args:
          - "-e"
          - "-E"
          - "http.enabled=true"
        livenessProbe:
{{ toYaml .Values.importer_rdbms.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.importer_rdbms.readinessProbe | indent 10 }}        
        env:
        - name: "SPRING_PROFILES_ACTIVE"
          value: "{{ .Values.operations.SPRING_PROFILES_ACTIVE }}"
        - name: "DATASOURCE_CORE_USERNAME"
          value: "{{ .Values.importer_rdbms.datasource.username }}" 
        - name: "DATASOURCE_CORE_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "importer-rdbms-secret"
              key: "database-password"
        - name: "DATASOURCE_CORE_HOST"
          value: "{{ .Values.importer_rdbms.datasource.host }}"
        - name: "DATASOURCE_CORE_PORT"
          value: "{{ .Values.importer_rdbms.datasource.port }}"
        - name: "DATASOURCE_CORE_SCHEMA"
          value: "{{ .Values.importer_rdbms.datasource.schema }}"
        - name: "LOGGING_LEVEL_ROOT"
          value: "{{ .Values.importer_rdbms.LOGGING_LEVEL_ROOT }}"
        - name: "LOGGING_PATTERN_CONSOLE"
          value: "{{ .Values.importer_rdbms.LOGGING_PATTERN_CONSOLE }}"
        - name: "JAVA_TOOL_OPTIONS"
          value: "{{ .Values.importer_rdbms.javaToolOptions}}"
{{- if .Values.importer_rdbms.extraEnvs | default .Values.importer_rdbms.deployment.extraEnvs }}
{{ toYaml ( .Values.importer_rdbms.extraEnvs | default .Values.importer_rdbms.deployment.extraEnvs ) | indent 8 }}
{{- end }}
        envFrom: {{ toYaml ( .Values.importer_rdbms.envFrom | default .Values.importer_rdbms.deployment.envFrom ) | nindent 10 }}
        securityContext: {{ toYaml ( .Values.importer_rdbms.podSecurityContext | default .Values.importer_rdbms.deployment.securityContext ) | nindent 10 }}
        volumeMounts:
        {{- range .Values.secretMounts | default .Values.importer_rdbms.deployment.secretMounts }}
        - name: {{ .name }}
          mountPath: {{ .path }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- range $path, $config := .Values.ph-ee-importer-rdbmsConfig }}
        - name: ph-ee-importer-rdbms-config
          mountPath: /usr/share/ph-ee-importer-rdbms/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{ else }}
        {{- range $path, $config := .Values.importer_rdbms.deployment.ph-ee-importer-rdbmsConfig }}
        - name: ph-ee-importer-rdbms-config
          mountPath: /usr/share/ph-ee-importer-rdbms/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{- end }}
        {{- end }}
        {{- if .Values.importer_rdbms.extraVolumeMounts | default .Values.importer_rdbms.deployment.extraVolumeMounts }}
{{ toYaml ( .Values.importer_rdbms.extraVolumeMounts | default .Values.importer_rdbms.deployment.extraVolumeMounts ) | indent 8 }}
        {{- end }}
      {{- if .Values.importer_rdbms.extraContainers }}
{{ tpl .Values.importer_rdbms.extraContainers . | indent 6 }}
      {{- end }}
{{- end }}