apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: mpesa-secret-roster
type: Opaque
data:
  client-key: {{ .Values.mpesa.accounts.roster.client_key | b64enc }}
  client-secret: {{ .Values.mpesa.accounts.roster.client_secret | b64enc }}
  pass-key: {{ .Values.mpesa.accounts.roster.pass_key | b64enc }}

---
apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: mpesa-secret-paygops
type: Opaque
data:
  client-key: {{ .Values.mpesa.accounts.paygops.client_key | b64enc }}
  client-secret: {{ .Values.mpesa.accounts.paygops.client_secret | b64enc }}
  pass-key: {{ .Values.mpesa.accounts.paygops.pass_key | b64enc }}
