{{- if .Values.mock_oracle.enabled -}}

apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: "mock_oracle"
  labels:
    app: mock-oracle
spec:
  replicas: {{ .Values.mock_oracle.replicas }}
  selector:
    matchLabels:
      app: mock-oracle
  template:
    metadata:
      labels:
        app: mock-oracle
      annotations:
{{- if .Values.mock_oracle.deployment.annotations }}
{{ toYaml .Values.mock_oracle.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: mock-oracle
          image: "{{ .Values.mock_oracle.image }}"
          imagePullPolicy: "{{ .Values.mock_oracle.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.mock_oracle.limits.memory }}"
              cpu: "{{ .Values.mock_oracle.limits.cpu }}"
            requests:
              memory: "{{ .Values.mock_oracle.requests.memory }}"
              cpu: "{{ .Values.mock_oracle.requests.cpu }}"
          ports:
            - containerPort: 4100
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
{{- end }}