{{- if .Values.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-importer-es
  labels:
    app: ph-ee-importer-es
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ph-ee-importer-es
  template:
    metadata:
      labels:
        app: ph-ee-importer-es
    spec:
      initContainers:
      {{- with .Values.extraInitContainers }}
      {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: ph-ee-importer-es
          image: "{{ .Values.image }}"
          imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.limits.memory }}"
              cpu: "{{ .Values.limits.cpu }}"
            requests:
              memory: "{{ .Values.requests.memory }}"
              cpu: "{{ .Values.requests.cpu }}"
          env:
          - name: "reporting.enabled"
            value: "{{ .Values.reporting.enabled }}"
          - name: "LOGGING_LEVEL_ROOT"
            value: "{{ .Values.global.LOGGING_LEVEL_ROOT }}"
          - name: "importer_elasticsearch_url"
            value: "{{ .Values.importer_elasticsearch_url}}"
          - name: "JAVA_TOOL_OPTIONS"
            value: "{{ .Values.javaToolOptions}}"
          - name: "LOGGING_PATTERN_CONSOLE"
            value: "{{ .Values.global.LOGGING_PATTERN_CONSOLE}}"
          - name: "reporting.fields.amount"
            value: "{{ .Values.reporting.fields.amount }}"
          - name: "reporting.fields.accountId"
            value: "{{ .Values.reporting.fields.accountId }}"
          - name: "reporting.fields.errorCode"
            value: "{{ .Values.reporting.fields.errorCode }}"
          - name: "reporting.fields.errorDescription"
            value: "{{ .Values.reporting.fields.errorDescription }}"
          - name: "reporting.fields.externalId"
            value: "{{ .Values.reporting.fields.externalId }}"
          - name: "reporting.fields.initiator"
            value: "{{ .Values.reporting.fields.initiator }}"
          - name: "reporting.fields.initiatorType"
            value: "{{ .Values.reporting.fields.initiatorType }}"
          - name: "reporting.fields.isNotificationsFailureEnabled"
            value: "{{ .Values.reporting.fields.isNotificationsFailureEnabled }}"
          - name: "reporting.fields.isNotificationsSuccessEnabled"
            value: "{{ .Values.reporting.fields.isNotificationsSuccessEnabled }}"
          - name: "reporting.fields.mpesaTransactionId"
            value: "{{ .Values.reporting.fields.mpesaTransactionId }}"
          - name: "reporting.fields.mpesaTransactionStatusRetryCount"
            value: "{{ .Values.reporting.fields.mpesaTransactionStatusRetryCount }}"
          - name: "reporting.fields.originDate"
            value: "{{ .Values.reporting.fields.originDate }}"
          - name: "reporting.fields.partyLookupFailed"
            value: "{{ .Values.reporting.fields.partyLookupFailed }}"
          - name: "reporting.fields.phoneNumber"
            value: "{{ .Values.reporting.fields.phoneNumber }}"
          - name: "reporting.fields.processDefinitionKey"
            value: "{{ .Values.reporting.fields.processDefinitionKey }}"
          - name: "reporting.fields.processInstanceKey"
            value: "{{ .Values.reporting.fields.processInstanceKey }}"
          - name: "reporting.fields.scenario"
            value: "{{ .Values.reporting.fields.scenario }}"
          - name: "reporting.fields.tenantId"
            value: "{{ .Values.reporting.fields.tenantId }}"
          - name: "reporting.fields.timer"
            value: "{{ .Values.reporting.fields.timer }}"
          - name: "reporting.fields.timestamp"
            value: "{{ .Values.reporting.fields.timestamp }}"
          - name: "reporting.fields.transactionFailed"
            value: "{{ .Values.reporting.fields.transactionFailed }}"
          - name: "reporting.fields.transactionId"
            value: "{{ .Values.reporting.fields.transactionId }}"
          - name: "reporting.fields.transferCreateFailed"
            value: "{{ .Values.reporting.fields.transferCreateFailed }}"
          - name: "reporting.fields.transferSettlementFailed"
            value: "{{ .Values.reporting.fields.transferSettlementFailed }}"
          - name: "reporting.fields.transferResponseCREATE"
            value: "{{ .Values.reporting.fields.transferResponseCREATE }}"
          - name: "reporting.fields.ams"
            value: "{{ .Values.reporting.fields.ams }}"
          - name: "reporting.fields.currency"
            value: "{{ .Values.reporting.fields.currency }}"
          - name: "reporting.fields.clientCorrelationId"
            value: "{{ .Values.reporting.fields.clientCorrelationId }}"
          - name: "reporting.fields.errorInformation"
            value: "{{ .Values.reporting.fields.errorInformation }}"
          - name: "reporting.fields.customData"
            value: "{{ .Values.reporting.fields.customData }}"
          - name: "reporting.fields.confirmationReceived"
            value: "{{ .Values.reporting.fields.confirmationReceived }}"
          - name: "ELASTICSEARCH_SECURITY_ENABLED"
            value: "{{ .Values.elasticsearch_security_enabled }}"
          - name: "ELASTICSEARCH_SSLVERIFICATION"
            value: "{{ .Values.elasticsearch_sslverification }}"
          - name: "ELASTICSEARCH_USERNAME"
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: username
          - name: "ELASTICSEARCH_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: password
{{- if .Values.extraEnvs | default .Values.deployment.extraEnvs }}
{{ toYaml ( .Values.extraEnvs | default .Values.deployment.extraEnvs ) | indent 10 }}
{{- end }}        
          envFrom: {{ toYaml ( .Values.envFrom | default .Values.deployment.envFrom ) | nindent 12 }}
          securityContext: {{ toYaml ( .Values.podSecurityContext | default .Values.deployment.securityContext ) | nindent 12 }}              


{{- end }}
