# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.ph_ee_connector_ams_mifos.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ph-ee-connector-ams-mifos.fullname" . }}
  labels:
    app: "{{ template "ph-ee-connector-ams-mifos.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: '{{ .Release.Service }}'

  {{- if .Values.ph_ee_connector_ams_mifos.deployment.annotations }}
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.ph_ee_connector_ams_mifos.replicas }}
  selector:
    matchLabels:
      app: "{{ template "ph-ee-connector-ams-mifos.fullname" . }}"
  template:
    metadata:
      annotations:
{{- if .Values.ph_ee_connector_ams_mifos.deployment.annotations }}
{{ toYaml .Values.ph_ee_connector_ams_mifos.deployment.annotations | indent 8 }}
{{- end }}
        configChecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
      labels:
        app: '{{ template "ph-ee-connector-ams-mifos.fullname" . }}'
        chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    spec:
      affinity: {{ toYaml .Values.ph_ee_connector_ams_mifos.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.ph_ee_connector_ams_mifos.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.ph_ee_connector_ams_mifos.tolerations | default .Values.ph_ee_connector_ams_mifos.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.ph_ee_connector_ams_mifos.priorityClassName }}
      priorityClassName: {{ .Values.ph_ee_connector_ams_mifos.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template "ph-ee-connector-ams-mifos.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.ph_ee_connector_ams_mifos.terminationGracePeriod }}
      {{- if .Values.ph_ee_connector_ams_mifos.deployment.hostAliases }}
      hostAliases: {{ toYaml .Values.ph_ee_connector_ams_mifos.deployment.hostAliases | nindent 8 }}
      {{- end }}
      volumes:
      {{- range .Values.ph_ee_connector_ams_mifos.secretMounts | default .Values.ph_ee_connector_ams_mifos.deployment.secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      {{- if .Values.ph-ee-connector-ams-mifosConfig }}
      - name: ph-ee-connector-ams-mifos-config
        configMap:
          defaultMode: 0600
          name: {{ template "ph-ee-connector-ams-mifos.fullname" . }}-config
      {{- if .Values.ph_ee_connector_ams_mifos.extraVolumes | default .Values.ph_ee_connector_ams_mifos.deployment.extraVolumes }}
{{ toYaml ( .Values.ph_ee_connector_ams_mifos.extraVolumes | default .Values.ph_ee_connector_ams_mifos.deployment.extraVolumes ) | indent 6 }}
      {{- end }}

      {{- if .Values.ph_ee_connector_ams_mifos.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.ph_ee_connector_ams_mifos.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.ph_ee_connector_ams_mifos.extraInitContainers }}
      initContainers:
      # All the other beats accept a string here while
      # ph-ee-connector-ams-mifos accepts a valid yaml array. We're keeping
      # this as a backwards compatible change, while adding
      # also a way to pass a string as other templates to
      # make these implementations consistent.
      # https://github.com/elastic/helm-charts/issues/490
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
      {{- end }}
      {{- end }}
      containers:
      - name: "ph-ee-connector-ams-mifos"
        image: "{{ .Values.ph_ee_connector_ams_mifos.image }}:{{ .Values.ph_ee_connector_ams_mifos.imageTag }}"
        imagePullPolicy: "{{ .Values.ph_ee_connector_ams_mifos.imagePullPolicy }}"
        ports:
          - containerPort: 5000        
        resources:
            limits:
              memory: "{{ .Values.ph_ee_connector_ams_mifos.limits.memory }}"
              cpu: "{{ .Values.ph_ee_connector_ams_mifos.limits.cpu }}"
            requests:
              memory: "{{ .Values.ph_ee_connector_ams_mifos.requests.memory }}"
              cpu: "{{ .Values.ph_ee_connector_ams_mifos.requests.cpu }}"
        args:
          - "-e"
          - "-E"
          - "http.enabled=true"
        livenessProbe:
{{ toYaml .Values.ph_ee_connector_ams_mifos.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.ph_ee_connector_ams_mifos.readinessProbe | indent 10 }}       
        env:
        - name: "SPRING_PROFILES_ACTIVE"
          value: "{{ .Values.ph_ee_connector_ams_mifos.SPRING_PROFILES_ACTIVE }}"
        - name: "ams_local_enabled"
          value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_enabled }}"
        - name: "ams_local_interop_host"
          value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_interop_host }}"
        - name: "ams_local_customer_host"
          value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_customer_host }}"
        - name: "ams_local_account_host"
          value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_account_host }}"
        - name: "ams_local_auth_host"
          value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_auth_host }}"
        - name: "ams_local_loan_host"
          value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_loan_host }}"
        - name: "dfspids"
          value: "{{ .Values.ph_ee_connector_ams_mifos.dfspids }}"        
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- if .Values.ph_ee_connector_ams_mifos.extraEnvs | default .Values.ph_ee_connector_ams_mifos.deployment.extraEnvs }}
{{ toYaml ( .Values.ph_ee_connector_ams_mifos.extraEnvs | default .Values.ph_ee_connector_ams_mifos.deployment.extraEnvs ) | indent 8 }}
{{- end }}
        envFrom: {{ toYaml ( .Values.ph_ee_connector_ams_mifos.envFrom | default .Values.ph_ee_connector_ams_mifos.deployment.envFrom ) | nindent 10 }}
        securityContext: {{ toYaml ( .Values.ph_ee_connector_ams_mifos.podSecurityContext | default .Values.ph_ee_connector_ams_mifos.deployment.securityContext ) | nindent 10 }}
        volumeMounts:
        {{- range .Values.secretMounts | default .Values.ph_ee_connector_ams_mifos.deployment.secretMounts }}
        - name: {{ .name }}
          mountPath: {{ .path }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- range $path, $config := .Values.ph-ee-connector-ams-mifosConfig }}
        - name: ph-ee-connector-ams-mifos-config
          mountPath: /usr/share/ph-ee-connector-ams-mifos/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{ else }}
        {{- range $path, $config := .Values.ph_ee_connector_ams_mifos.deployment.ph-ee-connector-ams-mifosConfig }}
        - name: ph-ee-connector-ams-mifos-config
          mountPath: /usr/share/ph-ee-connector-ams-mifos/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{- end }}
        {{- end }}
        {{- if .Values.ph_ee_connector_ams_mifos.extraVolumeMounts | default .Values.ph_ee_connector_ams_mifos.deployment.extraVolumeMounts }}
{{ toYaml ( .Values.ph_ee_connector_ams_mifos.extraVolumeMounts | default .Values.ph_ee_connector_ams_mifos.deployment.extraVolumeMounts ) | indent 8 }}
        {{- end }}
      {{- if .Values.ph_ee_connector_ams_mifos.extraContainers }}
{{ tpl .Values.ph_ee_connector_ams_mifos.extraContainers . | indent 6 }}
      {{- end }}
{{- end }}