ph-ee-engine:
  
  channel:
    tenantPrimary:
      clientId: "mifos"
      clientSecret: "password"
      tenant: "greenbank"
    tenantSecondary:
      clientId: "mifos"
      clientSecret: "password"
      tenant: "bluebank"
    server:
      ssl:
        keyPassword: "password"
        keyStorePassword: "password"  

  # operations_app:
  #   ingress:
  #     enabled: false
  #     annotations: 
  #       kubernetes.io/ingress.class: nginx
  #       nginx.ingress.kubernetes.io/cors-allow-headers: 'platform-tenantid'
  #       nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS, DELETE
  #       nginx.ingress.kubernetes.io/cors-allow-origin: '*'
  #       nginx.ingress.kubernetes.io/enable-cors: "true"
  #     tls:
  #       - secretName: sandbox-secret
  #     hosts:
  #       - host: ops-bk.mifos.gazelle.test          
  #         paths: 
  #         - path: "/"
  #           backend:
  #             service:
  #               name: "ph-ee-operations-app"
  #               port:
  #                 number: 80

  # identity:
  #   hostname: "ops-bk.mifos.gazelle.test"
    
  integration_test:
    enabled: true
    gradle:
      command: ./gradlew test -Dcucumber.filter.tags="@gov"

account_mapper:
  enabled: true
  #IMAGETODO
  image: docker.io/openmf/ph-ee-identity-account-mapper:v1.6.0
  hostname: "identity-mapper.mifos.gazelle.test"
  LOGGING_LEVEL_ROOT: INFO    
  ingress:
    enabled: true
    className: nginx
    pathtype: Prefix
    annotations:
      nginx.ingress.kubernetes.io/access-control-allow-origin: 'true'
      nginx.ingress.kubernetes.io/cors-allow-headers: 'x-registering-institution-id'
      nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS, DELETE
      nginx.ingress.kubernetes.io/cors-allow-origin: '*'
      nginx.ingress.kubernetes.io/enable-cors: 'true'
    tls:
      - secretName: sandbox-secret
    hosts:
      - host: identity-mapper.mifos.gazelle.test
        paths:
        - path: "/"
          backend:
            service:
              name: "ph-ee-identity-account-mapper"
              port:
                number: 80
  deployment:
    annotations:
      deployTime: "{{ .Values.deployTime }}"
  async:
    core_pool_size: 10
    max_pool_size: 10
    queue_capacity: 100
  account_validation_enabled: "false"
  account_validator_connector: "gsma"
  spring:
    cache:
      time_to_live: 30
      time_to_idle: 30
      max_entries_heap: 1000
      max_byte_off_heap: 10
      max_byte_disk: 10
    datasource:
      url: jdbc:mysql:thin://operationsmysql:3306/identity_account_mapper
      username: mifos
      password: password
 
  
