{{- if .Values.post_installation_job.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-role-binding
subjects:
- kind: ServiceAccount
  name: job-creator
roleRef:
  kind: Role
  name: job-creator-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}