service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

enabled: ""
image: ""
imagePullPolicy: ""
SPRING_PROFILES_ACTIVE: ""
LOGGING_LEVEL_ROOT: "INFO"
camel_disable_ssl: true
application:
  bucket_name: "paymenthub-ee-dev"
zeebe:
  broker:
    contactpoint: ""
operations_app: 
  contactpoint: "http://ph-ee-operations-app:5000"
  endpoints:
    batch_summary: "/api/v1/batch"
    batch_detail: "/api/v1/batch/detail"
mock_payment_schema:
  contactpoint: "http://ph-ee-connector-mock-payment-schema:8080"
  endpoints:
    batch_summary: "/mockapi/v1/batch"
    batch_detail: "/mockapi/v1/batch/detail"
bulk_processor:
  contactpoint: "https://ph-ee-connector-bulk:8443"
  endpoints:
    batch_transaction: "/batchtransactions"
aws:
  region: "<region>"
  access_key: "<access key>" 
  secret_key: "<secret key>"  
limits:
  cpu: "500m"
  memory: "512M"
requests:
  cpu: "100m"
  memory: "512M"

# Enabling this will publicly expose your Elasticsearch instance.
# Only enable this if you have security enabled on your cluster
ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: "nginx"
  pathtype: ImplementationSpecific
  hosts:
    - host: ""
      paths:
        - path: /
  tls: []
  #  - secretName: sandbox-secret
  #    hosts:
  #      - chart-example.local

deployment:
  apiVersion: "apps/v1"
  annotations:
    deployTime: "{{ .Values.deployTime }}"
