{{- if .Values.enabled -}}
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-mock-payment-schema
  name: ph-ee-connector-mock-payment-schema
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: ph-ee-connector-mock-payment-schema
  sessionAffinity: None
  type: ClusterIP
{{- end }}  