{{- if .Values.messagegateway.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: message-gateway
  annotations:
{{- if .Values.messagegateway.ingress.annotations }}
{{ toYaml .Values.messagegateway.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.messagegateway.hostname }}"
      http:
        paths:
          - path: "{{ .Values.messagegateway.ingress.path }}"
            pathType: Prefix
            backend:
{{- if .Values.messagegateway.ingress.backend }}
{{ toYaml .Values.messagegateway.ingress.backend | indent 14 }}
{{- end }} 

  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}
