apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: messagegateway-secret
type: Opaque
data:
  api-key: "{{ .Values.messagegateway.secret.value.api_key | b64enc }}"
  project-id: "{{ .Values.messagegateway.secret.value.project_id | b64enc }}"
  database-password: "{{ .Values.messagegateway.MYSQL_PASSWORD | b64enc }}"
