# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.notifications.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ph-ee-connector-notifications.fullname" . }}
  labels:
    app: "{{ template "ph-ee-connector-notifications.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: '{{ .Release.Service }}'

  {{- if .Values.notifications.deployment.annotations }}
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.notifications.replicas }}
  selector:
    matchLabels:
      app: "{{ template "ph-ee-connector-notifications.fullname" . }}"
  template:
    metadata:
      annotations:
{{- if .Values.notifications.deployment.annotations }}
{{ toYaml .Values.notifications.deployment.annotations | indent 8 }}
{{- end }}
        configChecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
      labels:
        app: '{{ template "ph-ee-connector-notifications.fullname" . }}'
        chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    spec:
      affinity: {{ toYaml .Values.notifications.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.notifications.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.notifications.tolerations | default .Values.notifications.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.notifications.priorityClassName }}
      priorityClassName: {{ .Values.notifications.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template "ph-ee-connector-notifications.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.notifications.terminationGracePeriod }}
      {{- if .Values.notifications.deployment.hostAliases }}
      hostAliases: {{ toYaml .Values.notifications.deployment.hostAliases | nindent 8 }}
      {{- end }}
      volumes:
      {{- range .Values.notifications.secretMounts | default .Values.notifications.deployment.secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      {{- if .Values.ph-ee-connector-notificationsConfig }}
      - name: ph-ee-connector-notifications-config
        configMap:
          defaultMode: 0600
          name: {{ template "ph-ee-connector-notifications.fullname" . }}-config
      {{- if .Values.notifications.extraVolumes | default .Values.notifications.deployment.extraVolumes }}
{{ toYaml ( .Values.notifications.extraVolumes | default .Values.notifications.deployment.extraVolumes ) | indent 6 }}
      {{- end }}

      {{- if .Values.notifications.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.notifications.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.notifications.extraInitContainers }}
      initContainers:
      # All the other beats accept a string here while
      # ph-ee-connector-notifications accepts a valid yaml array. We're keeping
      # this as a backwards compatible change, while adding
      # also a way to pass a string as other templates to
      # make these implementations consistent.
      # https://github.com/elastic/helm-charts/issues/490
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
      {{- end }}
      {{- end }}
      containers:
      - name: "ph-ee-connector-notifications"
        image: "{{ .Values.notifications.image }}:{{ .Values.notifications.imageTag }}"
        imagePullPolicy: "{{ .Values.notifications.imagePullPolicy }}"
        ports:
          - containerPort: 5000        
        resources:
            limits:
              memory: "{{ .Values.notifications.limits.memory }}"
              cpu: "{{ .Values.notifications.limits.cpu }}"
            requests:
              memory: "{{ .Values.notifications.requests.memory }}"
              cpu: "{{ .Values.notifications.requests.cpu }}"
        args:
          - "-e"
          - "-E"
          - "http.enabled=true"
        livenessProbe:
{{ toYaml .Values.notifications.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.notifications.readinessProbe | indent 10 }}        
        env:
        - name: "SPRING_PROFILES_ACTIVE"
            value: "{{ .Values.notifications.SPRING_PROFILES_ACTIVE }}"
        - name: "ZEEBE_BROKER_CONTACTPOINT"
            value: "{{ .Values.notifications.zeebe_broker_contactpoint }}"
        - name: "HOSTCONFIG_HOST"
            value: "{{ .Values.notifications.hostconfig.host }}"
        - name: "HOSTCONFIG_PORT"
            value: "{{ .Values.notifications.hostconfig.port }}"
        - name: "MESSAGEGATEWAYCONFIG_HOST"
            value: "{{ .Values.notifications.MESSAGEGATEWAYCONFIG_HOST }}"
        - name: "NOTIFICATION_LOCAL_HOST"
            value: "{{ .Values.notifications.NOTIFICATION_LOCAL_HOST }}"
        - name: "NOTIFICATION_SUCCESS_ENABLED"
            value: "{{ .Values.notifications.NOTIFICATION_SUCCESS_ENABLED }}"
        - name: "NOTIFICATION_FAILURE_ENABLED"
            value: "{{ .Values.notifications.NOTIFICATION_FAILURE_ENABLED }}"
        - name: "LOGGING_LEVEL_ROOT"
            value:  "{{ .Values.notifications.LOGGING_LEVEL_ROOT }}"
{{- if .Values.notifications.extraEnvs | default .Values.notifications.deployment.extraEnvs }}
{{ toYaml ( .Values.notifications.extraEnvs | default .Values.notifications.deployment.extraEnvs ) | indent 8 }}
{{- end }}
        envFrom: {{ toYaml ( .Values.notifications.envFrom | default .Values.notifications.deployment.envFrom ) | nindent 10 }}
        securityContext: {{ toYaml ( .Values.notifications.podSecurityContext | default .Values.notifications.deployment.securityContext ) | nindent 10 }}
        volumeMounts:
        {{- range .Values.secretMounts | default .Values.notifications.deployment.secretMounts }}
        - name: {{ .name }}
          mountPath: {{ .path }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- range $path, $config := .Values.ph-ee-connector-notificationsConfig }}
        - name: ph-ee-connector-notifications-config
          mountPath: /usr/share/ph-ee-connector-notifications/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{ else }}
        {{- range $path, $config := .Values.notifications.deployment.ph-ee-connector-notificationsConfig }}
        - name: ph-ee-connector-notifications-config
          mountPath: /usr/share/ph-ee-connector-notifications/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{- end }}
        {{- end }}
        {{- if .Values.notifications.extraVolumeMounts | default .Values.notifications.deployment.extraVolumeMounts }}
{{ toYaml ( .Values.notifications.extraVolumeMounts | default .Values.notifications.deployment.extraVolumeMounts ) | indent 8 }}
        {{- end }}
      {{- if .Values.notifications.extraContainers }}
{{ tpl .Values.notifications.extraContainers . | indent 6 }}
      {{- end }}
{{- end }}