bpmns.tenants[0].id= ph_greenbank
bpmns.tenants[0].flows.payment-transfer= minimal_mock_fund_transfer_account_lookup-{dfspid}
bpmns.tenants[1].id= ph_bluebank
bpmns.tenants[1].flows.payment-transfer= minimal_mock_fund_transfer-{dfspid}
bpmns.tenants[1].flows.outbound-transfer-request= minimal_mock_transfer_request-{dfspid}
# bpmns.tenants[0].id= ph_greenbank
# bpmns.tenants[0].flows.payment-transfer= minimal_mock_fund_transfer-{dfspid}
# bpmns.tenants[0].flows.outbound-transfer-request= minimal_mock_transfer_request-{dfspid}