store.local.interop.host=https://FREDrhino.mifos.gazelle.test
store.local.customer.host=https://FREDrhino.mifos.gazelle.test
zeebe.broker.contactpoint={{ .Release.Name }}-zeebe-gateway:26500

security.oauth2.resource.jwt.key-uri=http://ops-bk.mifos.gazelle.test/oauth/token_key
rest.authorization.enabled=false
rest.authorization.host=http://ops-bk.mifos.gazelle.test

dfspids=greenbank, bluebank