# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.importer_es.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ph-ee-importer-es.fullname" . }}
  labels:
    app: "{{ template "ph-ee-importer-es.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: '{{ .Release.Service }}'

  {{- if .Values.importer_es.deployment.annotations }}
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.importer_es.replicas }}
  selector:
    matchLabels:
      app: "{{ template "ph-ee-importer-es.fullname" . }}"
  template:
    metadata:
      annotations:
{{- if .Values.importer_es.deployment.annotations }}
{{ toYaml .Values.importer_es.deployment.annotations | indent 8 }}
{{- end }}
        configChecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
      labels:
        app: '{{ template "ph-ee-importer-es.fullname" . }}'
        chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    spec:
      affinity: {{ toYaml .Values.importer_es.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.importer_es.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.importer_es.tolerations | default .Values.importer_es.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.importer_es.priorityClassName }}
      priorityClassName: {{ .Values.importer_es.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template "ph-ee-importer-es.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.importer_es.terminationGracePeriod }}
      {{- if .Values.importer_es.deployment.hostAliases }}
      hostAliases: {{ toYaml .Values.importer_es.deployment.hostAliases | nindent 8 }}
      {{- end }}
      volumes:
      {{- range .Values.importer_es.secretMounts | default .Values.importer_es.deployment.secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      {{- if .Values.ph-ee-importer-esConfig }}
      - name: ph-ee-importer-es-config
        configMap:
          defaultMode: 0600
          name: {{ template "ph-ee-importer-es.fullname" . }}-config
      {{- if .Values.importer_es.extraVolumes | default .Values.importer_es.deployment.extraVolumes }}
{{ toYaml ( .Values.importer_es.extraVolumes | default .Values.importer_es.deployment.extraVolumes ) | indent 6 }}
      {{- end }}

      {{- if .Values.importer_es.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.importer_es.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.importer_es.extraInitContainers }}
      initContainers:
      # All the other beats accept a string here while
      # ph-ee-importer-es accepts a valid yaml array. We're keeping
      # this as a backwards compatible change, while adding
      # also a way to pass a string as other templates to
      # make these implementations consistent.
      # https://github.com/elastic/helm-charts/issues/490
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
      {{- end }}
      {{- end }}
      containers:
      - name: "ph-ee-importer-es"
        image: "{{ .Values.importer_es.image }}:{{ .Values.importer_es.imageTag }}"
        imagePullPolicy: "{{ .Values.importer_es.imagePullPolicy }}"
        ports:
          - containerPort: 5000        
        resources:
            limits:
              memory: "{{ .Values.importer_es.limits.memory }}"
              cpu: "{{ .Values.importer_es.limits.cpu }}"
            requests:
              memory: "{{ .Values.importer_es.requests.memory }}"
              cpu: "{{ .Values.importer_es.requests.cpu }}"
        args:
          - "-e"
          - "-E"
          - "http.enabled=true"
        livenessProbe:
{{ toYaml .Values.importer_es.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.importer_es.readinessProbe | indent 10 }}        
        env:
        - name: "reporting.enabled"
          value: "{{ .Values.importer_es.reporting.enabled }}"
        - name: "logging_level_ROOT"
          value: "{{ .Values.importer_es.logging.level.root }}"
        - name: "importer_elasticsearch_url"
          value: "{{ .Values.importer_es.importer_elasticsearch_url }}"
        - name: "JAVA_TOOL_OPTIONS"
          value: "{{ .Values.importer_es.javaToolOptions}}"
        - name: "LOGGING_PATTERN_CONSOLE"
          value: "{{ .Values.importer_es.logging.pattern.console}}"
        - name: "reporting.fields.amount"
          value: "{{ .Values.importer_es.reporting.fields.amount }}"
        - name: "reporting.fields.accountId"
          value: "{{ .Values.importer_es.reporting.fields.accountId }}"
        - name: "reporting.fields.errorCode"
          value: "{{ .Values.importer_es.reporting.fields.errorCode }}"
        - name: "reporting.fields.errorDescription"
          value: "{{ .Values.importer_es.reporting.fields.errorDescription }}"
        - name: "reporting.fields.externalId"
          value: "{{ .Values.importer_es.reporting.fields.externalId }}"
        - name: "reporting.fields.initiator"
          value: "{{ .Values.importer_es.reporting.fields.initiator }}"
        - name: "reporting.fields.initiatorType"
          value: "{{ .Values.importer_es.reporting.fields.initiatorType }}"
        - name: "reporting.fields.isNotificationsFailureEnabled"
          value: "{{ .Values.importer_es.reporting.fields.isNotificationsFailureEnabled }}"
        - name: "reporting.fields.isNotificationsSuccessEnabled"
          value: "{{ .Values.importer_es.reporting.fields.isNotificationsSuccessEnabled }}"
        - name: "reporting.fields.mpesaTransactionId"
          value: "{{ .Values.importer_es.reporting.fields.mpesaTransactionId }}"
        - name: "reporting.fields.mpesaTransactionStatusRetryCount"
          value: "{{ .Values.importer_es.reporting.fields.mpesaTransactionStatusRetryCount }}"
        - name: "reporting.fields.originDate"
          value: "{{ .Values.importer_es.reporting.fields.originDate }}"
        - name: "reporting.fields.partyLookupFailed"
          value: "{{ .Values.importer_es.reporting.fields.partyLookupFailed }}"
        - name: "reporting.fields.phoneNumber"
          value: "{{ .Values.importer_es.reporting.fields.phoneNumber }}"
        - name: "reporting.fields.processDefinitionKey"
          value: "{{ .Values.importer_es.reporting.fields.processDefinitionKey }}"
        - name: "reporting.fields.processInstanceKey"
          value: "{{ .Values.importer_es.reporting.fields.processInstanceKey }}"
        - name: "reporting.fields.scenario"
          value: "{{ .Values.importer_es.reporting.fields.scenario }}"
        - name: "reporting.fields.tenantId"
          value: "{{ .Values.importer_es.reporting.fields.tenantId }}"
        - name: "reporting.fields.timer"
          value: "{{ .Values.importer_es.reporting.fields.timer }}"
        - name: "reporting.fields.timestamp"
          value: "{{ .Values.importer_es.reporting.fields.timestamp }}"
        - name: "reporting.fields.transactionFailed"
          value: "{{ .Values.importer_es.reporting.fields.transactionFailed }}"
        - name: "reporting.fields.transactionId"
          value: "{{ .Values.importer_es.reporting.fields.transactionId }}"
        - name: "reporting.fields.transferCreateFailed"
          value: "{{ .Values.importer_es.reporting.fields.transferCreateFailed }}"
        - name: "reporting.fields.transferSettlementFailed"
          value: "{{ .Values.importer_es.reporting.fields.transferSettlementFailed }}"
        - name: "reporting.fields.transferResponseCREATE"
          value: "{{ .Values.importer_es.reporting.fields.transferResponseCREATE }}"
        - name: "reporting.fields.ams"
          value: "{{ .Values.importer_es.reporting.fields.ams }}"
        - name: "reporting.fields.currency"
          value: "{{ .Values.importer_es.reporting.fields.currency }}"
        - name: "reporting.fields.clientCorrelationId"
          value: "{{ .Values.importer_es.reporting.fields.clientCorrelationId }}"
        - name: "reporting.fields.errorInformation"
          value: "{{ .Values.importer_es.reporting.fields.errorInformation }}"
        - name: "reporting.fields.customData"
          value: "{{ .Values.importer_es.reporting.fields.customData }}"
        - name: "reporting.fields.confirmationReceived"
          value: "{{ .Values.importer_es.reporting.fields.confirmationReceived }}"
        - name: "ELASTICSEARCH_SECURITY_ENABLED"
          value: "{{ .Values.importer_es.elasticsearch_security_enabled }}"
        - name: "ELASTICSEARCH_SSLVERIFICATION"
          value: "{{ .Values.importer_es.elasticsearch_sslverification }}"
        - name: "ELASTICSEARCH_USERNAME"
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: username
        - name: "ELASTICSEARCH_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: password
{{- if .Values.importer_es.extraEnvs | default .Values.importer_es.deployment.extraEnvs }}
{{ toYaml ( .Values.importer_es.extraEnvs | default .Values.importer_es.deployment.extraEnvs ) | indent 8 }}
{{- end }}
        envFrom: {{ toYaml ( .Values.importer_es.envFrom | default .Values.importer_es.deployment.envFrom ) | nindent 10 }}
        securityContext: {{ toYaml ( .Values.importer_es.podSecurityContext | default .Values.importer_es.deployment.securityContext ) | nindent 10 }}
        volumeMounts:
        {{- range .Values.secretMounts | default .Values.importer_es.deployment.secretMounts }}
        - name: {{ .name }}
          mountPath: {{ .path }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- range $path, $config := .Values.ph-ee-importer-esConfig }}
        - name: ph-ee-importer-es-config
          mountPath: /usr/share/ph-ee-importer-es/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{ else }}
        {{- range $path, $config := .Values.importer_es.deployment.ph-ee-importer-esConfig }}
        - name: ph-ee-importer-es-config
          mountPath: /usr/share/ph-ee-importer-es/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{- end }}
        {{- end }}
        {{- if .Values.importer_es.extraVolumeMounts | default .Values.importer_es.deployment.extraVolumeMounts }}
{{ toYaml ( .Values.importer_es.extraVolumeMounts | default .Values.importer_es.deployment.extraVolumeMounts ) | indent 8 }}
        {{- end }}
      {{- if .Values.importer_es.extraContainers }}
{{ tpl .Values.importer_es.extraContainers . | indent 6 }}
      {{- end }}
{{- end }}