{{- if .Values.enabled }}
apiVersion: batch/v1
kind: job
metadata:
  name: "integration-test-job"
  annotations:
    "helm.sh/hook": test-success
spec:
  template:
    metadata:
      name: "integration-test-job"
    spec:
      containers:
        - name: "integration-test-job"
          image: "{{ .Values.image }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          command: [ "/bin/bash" , "-c" ]
          args: 
            - {{ .Values.args }}
          env:
            - name: "OPERATIONS-APP_CONTACTPOINT"
              value: "{{ .Values.operations_app.contactpoint }}"
            - name: "BULK-PROCESSOR_CONTACTPOINT"
              value: "{{ .Values.bulk_processor.contactpoint }}"
            - name: "CHANNEL-CONNECTOR_CONTACTPOINT"
              value: "{{ .Values.channel_connector.contactpoint }}"
            - name: "CHANNEL_BASE-URL"
              value: "{{ .Values.channel.base_url }}"
            - name: "KAFKA_BROKERS"
              value: "{{ .Values.kafka.brokers }}"
            - name: "KAFKA_TOPICS"
              value: "{{ .Values.kafka.topics }}"
            - name: "KAFKA_CONSUMER_TIME_OUT_MS"
              value: "{{ .Values.kafka.consumerTimeoutMs }}"
            - name: "ZEEBE-OPERATIONS_CONTACTPOINT"
              value: "{{ .Values.zeebe_operations.contactpoint }}"
            - name: "ZEEBE-OPERATIONS_NO-OF-WORKFLOWS"
              value: "{{ .Values.zeebe_operations.no_of_workflows }}"
            - name: "MAX-RETRY-COUNT"
              value: "{{ .Values.max_retry_count }}"
            - name: "RETRY-INTERVAL"
              value: "{{ .Values.retry_intervals }}"
            - name: "DEFAULTS_TENANT"
              value: "{{ .Values.defaults.tenant }}"
            - name: "DEFAULTS_AUTHORIZATION"
              value: "{{ .Values.defaults.authorization }}"
            - name: "CHANNEL_BASE-URL"
              value: "{{ .Values.channel.base_url }}"
            - name: "LOAN_BASE-URL"
              value: "{{ .Values.loan.base_url }}"
            - name: "SAVINGS_BASE-URL"
              value: "{{ .Values.savings.base_url }}"
            - name: "SAVINGS_CONTACTPOINT"
              value: "{{ .Values.savings.contactpoint }}"
            - name: "MOCK_SERVER_PORT"
              value: "{{ .Values.mock_server.port }}"
            - name: "IDENTITY_ACCOUNT_MAPPER_CONTACTPOINT"
              value: "{{ .Values.identity_account_mapper.contactpoint }}"
            - name: "MIFOS_CONNECTOR_CONTACTPOINT"
              value: "{{ .Values.mifos_connector.contactpoint }}"
            - name: "AMSMIFOS_MOCK_BASE_URL"
              value: "{{ .Values.amsmifos.mock.base_url }}"
            - name: "MOCK_PAYMENT_SCHEMA_CONTACTPOINT"
              value: "{{ .Values.mock_payment_schema.contactpoint }}"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "CALLBACK_URL"
              value: "{{ .Values.callback_url }}"
            - name: "PAYBILL_MPESA_CONNECTOR_CONTACTPOINT"
              value: "{{ .Values.paybill.mpesa_connector.contactpoint }}"
            - name: VOUCHER_MANAGEMENT_CONTACTPOINT
              value: "{{ .Values.voucher_management.contactpoint }}"
          {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          resources:
            limits:
              memory: "{{ .Values.limits.memory }}"
              cpu: "{{ .Values.limits.cpu }}"
            requests:
              memory: "{{ .Values.requests.memory }}"
              cpu: "{{ .Values.requests.cpu }}"
      restartPolicy: "{{ .Values.restartPolicy }}"
  backoffLimit: "{{ .Values.backoffLimit }}"
{{- end }}