apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  template:
    spec:
      containers:
      - name: myjob
        image: docker.io/openmf/ph-ee-integration-test:v1.2.0
        command: [ "/bin/bash" , "-c", echo 'test' ]
      restartPolicy: OnFailure