apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
spec:
  template:
    spec:
      containers:
      - name: ph-ee-integration-test
        image: "{{ .Values.image }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        ports:
          - containerPort: "53013"
        command: [ "/bin/bash" , "-c" ]
        args: 
        - ./gradlew test -Dcucumber.filter.tags="@gov" ; echo 'Test complete' ; sleep 600 ; echo 'pod terminate'
        env:
        - name: "OPERATIONS_APP_CONTACTPOINT"
          value: "http://ph-ee-operations-app:80"
        - name: "BULK_PROCESSOR_CONTACTPOINT"
          value: "http://ph-ee-connector-bulk:80"
        - name: "CHANNEL_CONNECTOR_CONTACTPOINT"
          value: "https://ph-ee-connector-channel:80"
        - name: "KAFKA_BROKERS"
          value: "{{ .Values.kafka.brokers }}"
        - name: "KAFKA_TOPICS"
          value: "{{ .Values.kafka.topics }}"
        - name: "KAFKA_CONSUMERTIMEOUTMS"
          value: "{{ .Values.kafka.consumerTimeoutMs }}"
        - name: "ZEEBE_OPERATIONS_CONTACTPOINT"
          value: "{{ .Values.zeebe_operations.contactpoint }}"
        - name: "ZEEBE_OPERATIONS_NO-OF-WORKFLOWS"
          value: "{{ .Values.zeebe_operations.no_of_workflows }}"
        - name: "MAX_RETRY_COUNT"
          value: "{{ .Values.max_retry_count }}"
        - name: "RETRY_INTERVAL"
          value: "{{ .Values.retry_intervals }}"
        - name: "DEFAULTS_TENANT"
          value: "{{ .Values.defaults.tenant }}"
        - name: "DEFAULTS_AUTHORIZATION"
          value: "{{ .Values.defaults.authorization }}"
        - name: "CHANNEL_BASE-URL"
          value: "{{ .Values.channel.base_url }}"
        - name: "LOAN_BASE-URL"
          value: "{{ .Values.loan.base_url }}"
        - name: "SAVINGS_BASE-URL"
          value: "{{ .Values.savings.base_url }}"
        - name: CHANNEL_CONTACTPOINT
          value: "https://ph-ee-connector-channel:80"
        - name: SAVINGS_CONTACTPOINT
          value: "https://fineract-server:8443"
        - name: LOAN_CONTACTPOINT
          value: "https://fineract-server:8443"
        - name: MOCK_SERVER_PORT
          value: "53013"
        - name: IDENTITY_ACCOUNT_MAPPER_CONTACTPOINT
          value: "https://ph-ee-identity-account-mapper:80"
        - name: MIFOS_CONNECTOR_CONTACTPOINT
          value: "https://ph-ee-connector-ams-mifos:80"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "CALLBACK_URL"
          value: http://$(MY_POD_IP):53013
        - name: PAYBILL_MPESA_CONNECTOR_CONTACTPOINT
          value: "{{ .Values.paybill.mpesa_connector.contactpoint}}"
        resources:
          limits:
            memory: "{{ .Values.limits.memory }}"
            cpu: "{{ .Values.limits.cpu }}"
          requests:
            memory: "{{ .Values.requests.memory }}"
            cpu: "{{ .Values.requests.cpu }}"
      restartPolicy: OnFailure
  backoffLimit: 0