ingress:
  apiversion: networking.k8s.io/v1

service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1" 
  

enabled: false
image: ""
imageTag: latest
SPRING_PROFILES_ACTIVE: "bb"
LOGGING_LEVEL_ROOT: "INFO"
ams:
  local:
    enabled: false
paygops:
  authheader: ""
  base_url: "https://feature-test1.paygops.com/"
limits:
  cpu: "500m"
  memory: "512M"
requests:
  cpu: "100m"
  memory: "256M"
deployment:
  apiVersion: "apps/v1"
  annotations:
    deployTime: "{{ .Values.deployTime }}"