apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-mpesa"
  labels:
    app: ph-ee-connector-mpesa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-mpesa
  template:
    metadata:
      labels:
        app: ph-ee-connector-mpesa
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-mpesa
          image: danishfynarfin/ph-ee-connector-mpesa
          ports:
            - containerPort: 5000
          env:
            - name: spring.datasource.url
              value: jdbc:mysql:thin://operations-mysql:3306/messagegateway
            - name: spring.datasource.username
              value: mifos
            - name: spring.datasource.password
              value: password

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-mpesa
  name: ph-ee-connector-mpesa
  namespace: default
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-mpesa
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ph-ee-connector-mpesa
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: "{{ .Values.ph-ee-connector-mpesa.hostname }}"
      http:
        paths:
          - backend:
              serviceName: ph-ee-connector-mpesa
              servicePort: 80