{{- if .Values.redis.enabled -}}
apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: {{ .Values.redis.imagePullPolicy }}
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: {{ .Values.redis.voulumeMountName }}
              mountPath: {{ .Values.redis.voulumeMountPath }}
      volumes:
        - name: {{ .Values.redis.volumeName }}
          emptyDir: {}
---
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis

{{- end}}