apiVersion: batch/v1
kind: Job
metadata:
  name: "ph-ee-integration-test-job"
  annotations:
    "helm.sh/hook": test-success
spec:
  template:
    metadata:
      name: ph-ee-integration-test-job
    spec:
      containers:
      - name: ph-ee-integration-test
        image: docker.io/openmf/ph-ee-integration-test:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 53013
        command: [ "/bin/bash" , "-c" ]
        args: 
          - ./gradlew test -Dcucumber.filter.name="MFT-002" ; echo 'Test complete' ; sleep 600 ; echo 'pod terminate'
        env:
          - name: "OPERATIONS-APP_CONTACTPOINT"
            value: http://ph-ee-operations-app:80
          - name: "BULK-PROCESSOR_CONTACTPOINT"
            value: http://ph-ee-connector-bulk:80
          - name: "CHANNEL-CONNECTOR_CONTACTPOINT"
            value: https://ph-ee-connector-channel:80
          - name: "identity-account-mapper_contactpoint"
            value: http://ph-ee-identity-account-mapper:80
          - name: CHANNEL_CONTACTPOINT
            value: https://ph-ee-connector-channel:80
          - name: MOCK-SERVER_PORT
            value: "53013"  
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: "CALLBACK_URL"  
            value: http://$(MY_POD_IP):53013 
        resources:
          limits:
            cpu: "500m"
            memory: "3Gi"
            ephemeral-storage: 3Gi
          requests:
            cpu: "100m"
            memory: "2Gi"
            ephemeral-storage: 2Gi 
      terminationGracePeriodSeconds: 120
      restartPolicy: Never
  backoffLimit: 0
