{{- if .Values.operations.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: ph-ee-importer-rdbms
  labels:
    app: ph-ee-importer-rdbms
spec:
  replicas: {{ .Values.importer_rdbms.replicas }}
  selector:
    matchLabels:
      app: ph-ee-importer-rdbms
  template:
    metadata:
      labels:
        app: ph-ee-importer-rdbms
      annotations:
{{- if .Values.importer_rdbms.deployment.annotations }}
{{ toYaml .Values.importer_rdbms.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-importer-rdbms
          image: "{{ .Values.importer_rdbms.image }}:{{ .Values.importer_rdbms.imageTag }}"
          imagePullPolicy: "{{ .Values.importer_rdbms.imagePullPolicy }}"
          ports:
            - containerPort: 8000
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.operations.SPRING_PROFILES_ACTIVE }}"
            - name: "DATASOURCE_CORE_USERNAME"
              value: "{{ .Values.importer_rdbms.datasource.username }}" 
            - name: "DATASOURCE_CORE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "importer-rdbms-secret"
                  key: "database-password"
            - name: "DATASOURCE_CORE_HOST"
              value: "{{ .Values.importer_rdbms.datasource.host }}"
            - name: "DATASOURCE_CORE_PORT"
              value: "{{ .Values.importer_rdbms.datasource.port }}"
            - name: "DATASOURCE_CORE_SCHEMA"
              value: "{{ .Values.importer_rdbms.datasource.schema }}"
            - name: "LOGGING_LEVEL_ROOT"
              value: "{{ .Values.importer_rdbms.LOGGING_LEVEL_ROOT }}"
            - name: "LOGGING_PATTERN_CONSOLE"
              value: "{{ .Values.importer_rdbms.LOGGING_PATTERN_CONSOLE }}"
            - name: "JAVA_TOOL_OPTIONS"
              value: "{{ .Values.importer_rdbms.javaToolOptions}}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
          resources:
            limits:
              memory: "{{ .Values.importer_rdbms.limits.memory }}"
              cpu: "{{ .Values.importer_rdbms.limits.cpu }}"
            requests:
              memory: "{{ .Values.importer_rdbms.requests.memory }}"
              cpu: "{{ .Values.importer_rdbms.requests.cpu }}"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
---
apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: importer-rdbms-secret
type: Opaque
data:
  database-password: {{ .Values.importer_rdbms.datasource.password | b64enc }}
{{- end }}