{{- if .Values.operations.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-operations-app"
  labels:
    app: ph-ee-operations-app
spec:
  replicas: {{ .Values.operations_app.replicas }}
  selector:
    matchLabels:
      app: ph-ee-operations-app
  template:
    metadata:
      labels:
        app: ph-ee-operations-app
      annotations:
{{- if .Values.operations_app.deployment.annotations }}
{{ toYaml .Values.operations_app.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-operations-app
          image: "{{ .Values.operations_app.image }}:{{ .Values.operations_app.imageTag }}"
          imagePullPolicy: "{{ .Values.operations_app.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /oauth/token_key
              port: 5000
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              memory: "{{ .Values.operations_app.limits.memory }}"
              cpu: "{{ .Values.operations_app.limits.cpu }}"
            requests:
              memory: "{{ .Values.operations_app.requests.memory }}"
              cpu: "{{ .Values.operations_app.requests.cpu }}"
          env:
            - name: "FINERACT_DATASOURCE_CORE_USERNAME"
              value: "{{ .Values.operations_app.datasource.username }}" 
            - name: "FINERACT_DATASOURCE_CORE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "operations-app-secret"
                  key: "database-password"
            - name: "FINERACT_DATASOURCE_CORE_HOST"
              value: "{{ .Values.operations_app.datasource.host }}"
            - name: "FINERACT_DATASOURCE_CORE_PORT"
              value: "{{ .Values.operations_app.datasource.port }}"
            - name: "FINERACT_DATASOURCE_CORE_SCHEMA"
              value: "{{ .Values.operations_app.datasource.schema }}"
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.operations_app.SPRING_PROFILES_ACTIVE }}"
            - name: "TOKEN_CLIENT_CHANNEL_SECRET"
              value: "{{ .Values.operations_app.token_client_channel_secret }}"
            - name: "TENANTS"
              value: "{{ .Values.operations_app.tenants }}"
            - name: "LOGGING_LEVEL_ROOT"
              value: "{{ .Values.operations_app.LOGGING_LEVEL_ROOT }}"
            - name: "LOGGING_PATTERN_CONSOLE"
              value: "{{ .Values.operations_app.LOGGING_PATTERN_CONSOLE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
            - -timeout=120s
            - -wait
            - tcp://{{ .Values.operations_app.datasource.host }}:3306
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-operations-app
  name: ph-ee-operations-app
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-operations-app
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: operations-app-secret
type: Opaque
data:
  database-password: {{ .Values.operations_app.datasource.password | b64enc }}
---
{{- if .Values.operations_app.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-operations-app
  annotations:
{{- if .Values.operations_app.ingress.annotations }}
{{ toYaml .Values.operations_app.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.operations_app.hostname }}"
      http:
        paths:
          - path: "{{ .Values.operations_app.ingress.path }}"
            pathType: Prefix
            backend:
{{- if .Values.operations_app.ingress.backend }}
{{ toYaml .Values.operations_app.ingress.backend | indent 14 }}
{{- end }}              

  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"

---
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-identity
  annotations:
{{- if .Values.operations_app.ingress.annotations }}
{{ toYaml .Values.operations_app.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.operations_app.hostname }}"
      http:
        paths:
          - path: /identity
            pathType: Prefix
            backend:
{{- if .Values.operations_app.ingress.backend }}
{{ toYaml .Values.operations_app.ingress.backend | indent 14 }}
{{- end }} 

  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}

{{- end }}
