apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: message-gateway
  name: message-gateway
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 9191
  selector:
    app: message-gateway
  sessionAffinity: None
  type: ClusterIP