{{- if .Values.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-connector
  labels:
    app: ph-ee-connector
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector
  template:
    metadata:
      labels:
        app: ph-ee-connector
      annotations:
{{- if .Values.deployment.annotations }}
{{ toYaml .Values.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      initContainers:
      {{- with .Values.extraInitContainers }}
      {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: ph-ee-connector
          image: "{{ .Values.image }}"
          ports:
            - containerPort: 8080
          imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.limits.memory }}"
              cpu: "{{ .Values.limits.cpu }}"
            requests:
              memory: "{{ .Values.requests.memory }}"
              cpu: "{{ .Values.requests.cpu }}"

          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.global.SPRING_PROFILES_ACTIVE }}"
            - name: "CAMEL_DISABLE-SSL"
              value: "{{ .Values.camel_disable_ssl }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "{{ .Release.Name }}-zeebe-gateway:26500"
            - name: "TENANTS"
              value: "{{ .Values.tenants }}"
            - name: "CLOUD_AWS_BUCKET-NAME"
              value: "{{ .Values.global.bucket_name }}"
            - name: "OPERATIONS-APP_CONTACTPOINT"
              value: "{{ .Values.operations_app.contactpoint }}"
            - name: "OPERATIONS-APP_ENDPOINTS_BATCH-SUMMARY"
              value: "{{ .Values.operations_app.endpoints.batch_summary }}"
            - name: "OPERATIONS-APP_ENDPOINTS_BATCH-DETAIL"
              value: "{{ .Values.operations_app.endpoints.batch_detail }}"
            - name: "MOCK-PAYMENT-SCHEMA_CONTACTPOINT"
              value: "{{ .Values.mock_payment_schema.contactpoint }}"
            - name: "MOCK-PAYMENT-SCHEMA_ENDPOINTS_BATCH-SUMMARY"
              value: "{{ .Values.mock_payment_schema.endpoints.batch_summary }}"
            - name: "MOCK-PAYMENT-SCHEMA_ENDPOINTS_BATCH-DETAIL"
              value: "{{ .Values.mock_payment_schema.endpoints.batch_detail }}"
            - name: "BULK-PROCESSOR_CONTACTPOINT"
              value: "{{ .Values.bulk_processor.contactpoint }}"
            - name: "BULK-PROCESSOR_ENDPOINTS_BATCH-TRANSACTION"
              value: "{{ .Values.bulk_processor.endpoints.batch_transaction }}"
            - name: "TENANT"
              value: "{{ .Values.global.tenant }}"
            - name: "CLOUD_AWS_REGION_STATIC"
              valueFrom:
                secretKeyRef:
                  name: "bulk-processor-secret"
                  key: "aws-region"
            - name: "CLOUD_AWS_S3BASEURL"
              value: {{.Values.global.s3BaseUrl}}
            - name: "AWS_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: "bulk-processor-secret"
                  key: "aws-access-key"
            - name: "AWS_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: "bulk-processor-secret"
                  key: "aws-secret-key"

{{- if .Values.extraEnvs | default .Values.deployment.extraEnvs }}
{{ toYaml ( .Values.extraEnvs | default .Values.deployment.extraEnvs ) | indent 10 }}
{{- end }}
          envFrom: {{ toYaml ( .Values.envFrom | default .Values.deployment.envFrom ) | nindent 12 }}
          securityContext: {{ toYaml ( .Values.podSecurityContext | default .Values.deployment.securityContext ) | nindent 12 }}
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
{{- end }}
