{{- if .Values.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ph-ee-operator-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ph-ee-operator-role
subjects:
  - kind: ServiceAccount
    name: payment-hub
    namespace: {{ .Release.Namespace }}
  {{- end -}}