{{- if .Values.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-connector-crm
  labels:
    app: ph-ee-connector-crm
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-crm
  template:
    metadata:
      labels:
        app: ph-ee-connector-crm
      annotations:
{{- if .Values.deployment.annotations }}
{{ toYaml .Values.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      containers:
        - name: ph-ee-connector-crm
          image: "{{ .Values.image }}"
          ports:
            - containerPort: 8080
          imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.limits.memory }}"
              cpu: "{{ .Values.limits.cpu }}"
            requests:
              memory: "{{ .Values.requests.memory }}"
              cpu: "{{ .Values.requests.cpu }}"
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8443
#              scheme: HTTPS
#            initialDelaySeconds: 20
#            periodSeconds: 180
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8443
#              scheme: HTTPS
#            initialDelaySeconds: 20
#            periodSeconds: 180
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "{{ .Release.Name }}-zeebe-gateway:26500"  
            - name: "DFSPIDS"
              value: "{{ .Values.global.DFSPIDS }}"
{{- if .Values.extraEnvs | default .Values.deployment.extraEnvs }}
{{ toYaml ( .Values.extraEnvs | default .Values.deployment.extraEnvs ) | indent 10 }}
{{- end }}        
          envFrom: {{ toYaml ( .Values.envFrom | default .Values.deployment.envFrom ) | nindent 12 }}
          securityContext: {{ toYaml ( .Values.podSecurityContext | default .Values.deployment.securityContext ) | nindent 12 }}              
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
{{- end }}
